FROM php:8.2-cli

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    libzip-dev \
    zip \
    nodejs \
    npm

# Install PHP extensions
RUN docker-php-ext-install zip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /app

# Copy project
COPY . .

# Install Laravel dependencies
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Install frontend (Vite)
RUN npm install
RUN npm run build

# Generate key (optional, nanti bisa pakai ENV juga)
RUN php artisan key:generate || true

# Expose port (Render pakai 10000)
EXPOSE 10000

# Start Laravel
CMD php artisan serve --host=0.0.0.0 --port=10000